import * as assert from 'assert';
import {
  ConversationCandidate,
  belongsToCwd,
  candidatesForCwd,
  formatBytes,
  formatCandidate,
  formatCandidateWithOwner,
  isSyntheticUserText,
  ownersOf,
  parseAiTitle,
  parseConversationHead,
} from '../../src/core/conversation';

/** 造一行 .jsonl。真实文件里 cwd 出现在大多数行上（mode/snapshot 行没有）。 */
const line = (o: object) => JSON.stringify(o);

const USER_LINE = (text: string, extra: object = {}) =>
  line({
    type: 'user', userType: 'external', isSidechain: false, cwd: '/a/b',
    message: { role: 'user', content: text }, ...extra,
  });

const c = (patch: Partial<ConversationCandidate> = {}): ConversationCandidate => ({
  id: 'aaaaaaaa-1111-2222-3333-444444444444',
  cwd: '/a/b',
  mtimeMs: 1_700_000_000_000,
  bytes: 2048,
  firstMessage: '改一下 bug',
  ...patch,
});

/** 斜杠命令那段免责声明 —— 本机 transcript 里实测到的原文。 */
const CAVEAT =
  '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. ' +
  'DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>';

/** `/clear` 这类命令产生的三段回显（`command-args` 实测常为空）。 */
const SLASH_CLEAR = [
  '<command-name>/clear</command-name>',
  '<command-message>clear</command-message>',
  '<command-args></command-args>',
].join('\n');

/** 命令的输出回显。 */
const STDOUT_ECHO = '<local-command-stdout>Conversation cleared</local-command-stdout>';

describe('parseConversationHead —— 从 .jsonl 头部提取 cwd 与首条用户消息', () => {
  it('跳过 mode / snapshot / attachment 之类的非用户行', () => {
    const text = [
      line({ type: 'mode', sessionId: 'x' }),
      line({ type: 'file-history-snapshot', snapshot: {} }),
      line({ type: 'attachment', cwd: '/a/b', attachment: {} }),
      USER_LINE('帮我改一下 bug'),
    ].join('\n');
    assert.deepStrictEqual(parseConversationHead(text), {
      cwd: '/a/b',
      firstMessage: '帮我改一下 bug',
    });
  });

  it('cwd 取自文件里记录的字段，不靠目录名转义规则反推', () => {
    // 实测 `_` 和 `.` 也会被换成 `-`，目录名不可靠
    const text = [line({ type: 'attachment', cwd: '/a/b_c.d/e' }), USER_LINE('hi')].join('\n');
    assert.strictEqual(parseConversationHead(text).cwd, '/a/b_c.d/e');
  });

  it('content 是分块数组时取第一个 text 块', () => {
    const text = [
      line({ type: 'attachment', cwd: '/a/b' }),
      line({
        type: 'user', userType: 'external', isSidechain: false, cwd: '/a/b',
        message: { role: 'user', content: [{ type: 'text', text: '分块消息' }] },
      }),
    ].join('\n');
    assert.strictEqual(parseConversationHead(text).firstMessage, '分块消息');
  });

  it('忽略 isSidechain 的子代理消息（不是用户敲的）', () => {
    const text = [
      line({ type: 'attachment', cwd: '/a/b' }),
      USER_LINE('子代理噪音', { isSidechain: true }),
      USER_LINE('真正由用户敲的'),
    ].join('\n');
    assert.strictEqual(parseConversationHead(text).firstMessage, '真正由用户敲的');
  });

  it('忽略只有 tool_result 的 user 行（那是工具回执，不是用户消息）', () => {
    const text = [
      line({ type: 'attachment', cwd: '/a/b' }),
      line({
        type: 'user', userType: 'external', isSidechain: false,
        message: { role: 'user', content: [{ type: 'tool_result', content: 'x' }] },
      }),
      USER_LINE('用户说的话'),
    ].join('\n');
    assert.strictEqual(parseConversationHead(text).firstMessage, '用户说的话');
  });

  it('末行被截断（只读了文件头部）不抛错，已解析出的部分保留', () => {
    const text = [line({ type: 'attachment', cwd: '/a/b' }), '{"type":"user","message":{"conten'].join('\n');
    assert.deepStrictEqual(parseConversationHead(text), { cwd: '/a/b' });
  });

  it('压平换行（含换行）—— QuickPick 的 label 是 pre + overflow:hidden，不压平就只剩第一行', () => {
    const text = [line({ type: 'attachment', cwd: '/a/b' }), USER_LINE('第一行\n\n第二行   第三行')].join('\n');
    assert.strictEqual(parseConversationHead(text).firstMessage, '第一行 第二行 第三行');
  });

  it('★ 常规长度的原文逐字保留、不被截断（本轮的核心行为）', () => {
    // 旧版这里压到 60 字。用户要的是**他自己敲的那句话**：只压平空白，
    // 不改写、不截短 —— 300 字（FIRST_MESSAGE_MAX）只是防「粘贴几万字」的
    // 兜底，正常永远轮不到它来截断。
    const msg = '把 vscode-tmux-terminals 里选择框的第二行去掉，只留首条用户消息的原文，不要截短，也不要改写';
    const text = [line({ type: 'attachment', cwd: '/a/b' }), USER_LINE(msg)].join('\n');
    const got = parseConversationHead(text).firstMessage;
    assert.strictEqual(got, msg);
    assert.ok(got !== undefined && !got.endsWith('…'), '常规长度不该出现省略号');
  });

  it('超过兜底上限（300 字）才截断成 `…`；恰好 300 字不截', () => {
    const headOf = (n: number) =>
      parseConversationHead(
        [line({ type: 'attachment', cwd: '/a/b' }), USER_LINE('x'.repeat(n))].join('\n'),
      ).firstMessage;

    const exact = headOf(300);
    assert.strictEqual(exact?.length, 300, '恰好等于上限时不截断');
    assert.ok(exact !== undefined && !exact.endsWith('…'));

    const over = headOf(500);
    assert.ok(over !== undefined && over.length <= 301, `实际长度 ${over?.length}`);
    assert.ok(over !== undefined && over.endsWith('…'));
  });

  it('什么都解析不出来时返回空对象（绝不编造）', () => {
    assert.deepStrictEqual(parseConversationHead(''), {});
    assert.deepStrictEqual(parseConversationHead('不是 json\n{也,不是}'), {});
  });
});

describe('isSyntheticUserText —— 斜杠命令的合成包裹消息', () => {
  it('caveat 独占一条 → 合成', () => {
    assert.strictEqual(isSyntheticUserText(CAVEAT), true);
  });

  it('/clear 的三段命令回显 → 合成；再拼上输出回显仍是合成', () => {
    assert.strictEqual(isSyntheticUserText(SLASH_CLEAR), true);
    assert.strictEqual(isSyntheticUserText([SLASH_CLEAR, STDOUT_ECHO].join('\n')), true);
  });

  it('★ 正文里引用了 <command-name> 的提问不算合成（防误杀的关键）', () => {
    assert.strictEqual(isSyntheticUserText('为什么 <command-name>/clear</command-name> 会清掉上下文？'), false);
    // 整段命令回显被引用、外面还裹着自己的话 → 剥完仍有正文
    assert.strictEqual(isSyntheticUserText(`这句里的 ${SLASH_CLEAR} 是什么意思？`), false);
  });

  it('包裹块后面跟着真实正文 → 不算合成', () => {
    assert.strictEqual(isSyntheticUserText(`${CAVEAT}\n顺便把那个 bug 也修了`), false);
  });

  it('空串 / 纯空白同样算「不是用户敲的话」', () => {
    assert.strictEqual(isSyntheticUserText(''), true);
    assert.strictEqual(isSyntheticUserText('  \n\t '), true);
  });

  it('没闭合的标签不剥（剥不干净就成了猜，交给 JSON.parse 那层挡）', () => {
    assert.strictEqual(isSyntheticUserText('<local-command-caveat>Caveat: 半截'), false);
  });
});

describe('parseConversationHead —— 跳过斜杠命令的合成包裹消息', () => {
  it('★ 首条是 local-command-caveat → 取到后面那条真实提问', () => {
    const text = [
      line({ type: 'attachment', cwd: '/a/b' }),
      USER_LINE(CAVEAT),
      USER_LINE('帮我把这个 bug 修了'),
    ].join('\n');
    assert.deepStrictEqual(parseConversationHead(text), {
      cwd: '/a/b',
      firstMessage: '帮我把这个 bug 修了',
    });
  });

  it('★ 首条是 /clear 的命令回显 → 同样跳过（连着输出回显一起）', () => {
    const text = [
      line({ type: 'attachment', cwd: '/a/b' }),
      USER_LINE(SLASH_CLEAR),
      USER_LINE(STDOUT_ECHO),
      USER_LINE('接着聊 Krita 编译'),
    ].join('\n');
    assert.strictEqual(parseConversationHead(text).firstMessage, '接着聊 Krita 编译');
  });

  it('用户在提问里引用 <command-name> → 正常当作首条消息（不误杀）', () => {
    const text = [
      line({ type: 'attachment', cwd: '/a/b' }),
      USER_LINE('为什么 <command-name>/clear</command-name> 会清掉上下文？'),
    ].join('\n');
    assert.strictEqual(
      parseConversationHead(text).firstMessage,
      '为什么 <command-name>/clear</command-name> 会清掉上下文？',
    );
  });

  it('全是合成消息、压根没有真实提问 → 不给 firstMessage（调用方据此回退「（无首条消息）」）', () => {
    const text = [
      line({ type: 'attachment', cwd: '/a/b' }),
      USER_LINE(CAVEAT),
      USER_LINE(SLASH_CLEAR),
    ].join('\n');
    assert.deepStrictEqual(parseConversationHead(text), { cwd: '/a/b' });
    // 落进列表时就是空串 —— formatCandidate 回退成「（无首条消息）」
    assert.ok(formatCandidate(c({ firstMessage: '' })).includes('（无首条消息）'));
  });
});

describe('belongsToCwd —— 对话归属判据', () => {
  it('精确相等才算同一条目', () => {
    assert.strictEqual(belongsToCwd('/a/b', '/a/b'), true);
  });
  it('忽略末尾斜杠差异', () => {
    assert.strictEqual(belongsToCwd('/a/b/', '/a/b'), true);
    assert.strictEqual(belongsToCwd('/a/b', '/a/b///'), true);
  });
  it('★ 前缀相近不是同一个目录（/a/b 与 /a/bc）', () => {
    assert.strictEqual(belongsToCwd('/a/bc', '/a/b'), false);
    assert.strictEqual(belongsToCwd('/a/b/c', '/a/b'), false);
  });
  it('完全不同 / 空串 → false', () => {
    assert.strictEqual(belongsToCwd('/x', '/a/b'), false);
    assert.strictEqual(belongsToCwd('', '/a/b'), false);
    assert.strictEqual(belongsToCwd('/a/b', ''), false);
  });
});

describe('candidatesForCwd —— 候选枚举', () => {
  it('只留下该 cwd 的，并按 mtime 倒序（新的在前）', () => {
    const items = [
      c({ id: 'old', mtimeMs: 100, cwd: '/a/b' }),
      c({ id: 'other', mtimeMs: 999, cwd: '/other' }),
      c({ id: 'new', mtimeMs: 500, cwd: '/a/b' }),
    ];
    assert.deepStrictEqual(candidatesForCwd(items, '/a/b').map((x) => x.id), ['new', 'old']);
  });
  it('mtime 相同时按 id 稳定排序（避免每次弹出顺序不同）', () => {
    const items = [c({ id: 'bbb', mtimeMs: 1 }), c({ id: 'aaa', mtimeMs: 1 })];
    assert.deepStrictEqual(candidatesForCwd(items, '/a/b').map((x) => x.id), ['aaa', 'bbb']);
  });
  it('没有归属该 cwd 的对话时返回空数组', () => {
    assert.deepStrictEqual(candidatesForCwd([c({ cwd: '/other' })], '/a/b'), []);
  });
});

describe('formatBytes / formatCandidate —— QuickPick 显示', () => {
  it('体积分档可读', () => {
    assert.strictEqual(formatBytes(512), '512 B');
    assert.strictEqual(formatBytes(1024), '1.0 KB');
    assert.strictEqual(formatBytes(1536), '1.5 KB');
    assert.strictEqual(formatBytes(20480), '20 KB');
    assert.strictEqual(formatBytes(1048576), '1.0 MB');
  });
  it('候选行含时间、首条消息原文、体积', () => {
    const s = formatCandidate(c({ firstMessage: '改一下 bug', bytes: 2048 }));
    assert.ok(s.includes('改一下 bug'), s);
    assert.ok(s.includes('2.0 KB'), s);
    assert.ok(/\d{4}-\d{2}-\d{2} \d{2}:\d{2}/.test(s), s);
  });
  it('没有首条消息时明说，不显示空档', () => {
    assert.ok(formatCandidate(c({ firstMessage: '' })).includes('（无首条消息）'));
  });
});

describe('ownersOf —— 哪些对话已经被别的条目绑走', () => {
  const E = (id: string, name: string, conversationId?: string) => ({ id, name, conversationId });

  it('收集「别的条目 → 它绑的对话」', () => {
    const m = ownersOf([E('a', '甲', 'conv-1'), E('b', '乙', 'conv-2')], 'self');
    assert.strictEqual(m.get('conv-1'), '甲');
    assert.strictEqual(m.get('conv-2'), '乙');
  });

  it('★ 跳过自己（自己当然绑着这条）', () => {
    const m = ownersOf([E('self', '我', 'conv-1')], 'self');
    assert.strictEqual(m.get('conv-1'), undefined);
  });

  it('跳过未绑定 / 空串 / 缺字段的条目', () => {
    const m = ownersOf([E('a', '甲'), E('b', '乙', ''), { id: 'c', name: '丙' }], 'self');
    assert.strictEqual(m.size, 0);
  });

  it('多条条目绑了同一个 id 时取先出现的（顺序稳定，不随后续条目抖动）', () => {
    const m = ownersOf([E('a', '甲', 'conv-1'), E('b', '乙', 'conv-1')], 'self');
    assert.strictEqual(m.get('conv-1'), '甲');
  });
});

describe('formatCandidateWithOwner —— 选择框里标注归属', () => {
  it('没人绑过时与普通行完全一致', () => {
    assert.strictEqual(formatCandidateWithOwner(c()), formatCandidate(c()));
  });
  it('已被绑走时附上归属者，用户能看出「这是别人的」', () => {
    const s = formatCandidateWithOwner(c(), 'UI_Worker-01');
    assert.ok(s.includes('已绑给「UI_Worker-01」'), s);
    assert.ok(s.startsWith(formatCandidate(c())), s);
  });
});

describe('parseAiTitle —— 从 transcript 尾部取最后一条 ai-title', () => {
  const ai = (title: string) => line({ type: 'ai-title', sessionId: 'x', aiTitle: title });

  it('单条 ai-title', () => {
    assert.strictEqual(parseAiTitle([USER_LINE('hi'), ai('继续 Krita 编译')].join('\n')), '继续 Krita 编译');
  });

  it('★ 多条时取**最后**一条（标题会变，最后一条才是当前标题）', () => {
    const text = [ai('旧标题'), USER_LINE('hi'), ai('中间标题'), ai('当前标题')].join('\n');
    assert.strictEqual(parseAiTitle(text), '当前标题');
  });

  it('aiTitle 里含被 JSON 转义的引号时原样取出', () => {
    assert.strictEqual(parseAiTitle(ai('他说"改一下"')), '他说"改一下"');
  });

  it('一条都没有 / 空串 → undefined', () => {
    assert.strictEqual(parseAiTitle([USER_LINE('hi')].join('\n')), undefined);
    assert.strictEqual(parseAiTitle(''), undefined);
  });

  it('aiTitle 是空串 / 非字符串 → 跳过（不当作标题）', () => {
    assert.strictEqual(parseAiTitle([line({ type: 'ai-title', aiTitle: '' }), ai('真标题')].join('\n')), '真标题');
    assert.strictEqual(parseAiTitle(line({ type: 'ai-title', aiTitle: 42 })), undefined);
  });

  it('★ 首行被截断（尾部窗口的起点落在一条记录中间）不抛且仍能取到后面的标题', () => {
    const broken = '{"type":"mode","sessionId":"x","cwd":"/a/b_c';
    assert.strictEqual(parseAiTitle([broken, ai('窗口内的标题')].join('\n')), '窗口内的标题');
  });

  it('★ ai-title 之后还有别的记录时仍要取到（真实 transcript 里标题几乎不在末行）', () => {
    const text = [ai('旧标题'), ai('当前标题'), USER_LINE('起了标题之后又聊了几句')].join('\n');
    assert.strictEqual(parseAiTitle(text), '当前标题');
  });
});
