/**
 * 「条目 ↔ claude 对话」的纯逻辑：候选枚举的解析与筛选、显示格式化。
 *
 * 本文件刻意不依赖 vscode，也不碰文件系统（IO 在 src/conversationFiles.ts），
 * 以便脱离编辑器直接单测。
 *
 * 背景（2026-09-10，实测结论，勿改）：
 * - `claude --resume <uuid>` **是按 cwd 作用域**的：从别的 cwd 运行会报
 *   `No conversation found with session ID`。所以恢复必须在条目自己的 cwd
 *   里 launch —— 扩展本来就是用 `-c cwd` 建会话，天然满足。
 * - 会话文件里记录了 `"cwd":"<绝对路径>"` 字段。**枚举候选一律按这个字段
 *   筛，不要去猜 project 目录名的转义规则**（实测 `_` 和 `.` 也会被换成
 *   `-`，规则不可靠）。
 * - claude 进程不长期持有 .jsonl 的 fd，无法从 /proc 反查运行中会话的 id，
 *   因此绑定关系只能由扩展自己记（见 types.ts 的 conversationId）。
 */

/** 一条可接回的对话（由 ~/.claude/projects 下的 .jsonl 枚举而来）。 */
export interface ConversationCandidate {
  /** 对话 id = 会话文件名（去掉 .jsonl），即 `--resume` 的参数 */
  id: string;
  /** 会话文件里记录的 cwd —— 权威的归属判据 */
  cwd: string;
  /** 文件 mtime（毫秒），用于倒序 */
  mtimeMs: number;
  /** 文件体积（字节），用于在列表里辨认 */
  bytes: number;
  /** 首条用户消息的**原文**（只压平空白，不压缩语义）；取不到为空串 */
  firstMessage: string;
}

/** 首条用户消息在选择框里最多带多少个字符。
 *
 * 这不是为了「一行放得下」—— 放不下是 VS Code 那一行自己截断的事，比这个数
 * 早得多。这是**上限的兜底**：粘贴几万字进会话是常事，而这段文本要随每一项
 * 候选走一遍渲染与进程间传递，不设上限就是白白搬运。取 300 —— 约为最宽的
 * 选择框一行能显示的两倍多，正常永远轮不到它来截断。 */
const FIRST_MESSAGE_MAX = 300;

/** 从 user 消息的 content 里取纯文本（可能是字符串，也可能是分块数组）。 */
function firstText(content: unknown): string | undefined {
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) {
    for (const block of content) {
      if (typeof block !== 'object' || block === null) continue;
      const b = block as { type?: unknown; text?: unknown };
      // 只认 text 块：tool_result 是工具回执，不是用户敲进去的话
      if (b.type === 'text' && typeof b.text === 'string') return b.text;
    }
  }
  return undefined;
}

/**
 * 压平空白（**含换行**）并截断。
 *
 * 压平是硬约束，不是美化：QuickPick 的 label 在 VS Code 里是 `white-space:
 * pre` + 行高钉死 + `overflow:hidden`，**换行不会折行、会被裁掉**。多行的一条
 * 消息若原样塞进去，会显示成「只有第一行、后面全没了」，看起来像丢了内容。
 * 压成一行至少让截断发生在行尾、且有省略号。
 *
 * max 默认取 FIRST_MESSAGE_MAX（上限的兜底，见那里的说明）；300 只是防「粘贴
 * 几万字」这类极端输入白白搬运，正常永远轮不到它来截断 —— 真正的截断发生在
 * VS Code 那一行，比它早得多。
 */
function condense(text: string, max: number = FIRST_MESSAGE_MAX): string {
  const flat = text.replace(/\s+/g, ' ').trim();
  return flat.length > max ? `${flat.slice(0, max)}…` : flat;
}

/**
 * claude 把**斜杠命令**写成合成的 user 消息。它不是用户敲进去的话，但长得和
 * 用户消息一模一样 —— 不识别的话，一条以 `/clear` 开头的会话，其首条 user
 * 消息就是这些包裹文本，列表里整个首条消息都成了噪音。
 *
 * 下面这几个标签是**本机 transcript 实测到的原文**，不是猜的：
 * - `local-command-caveat` —— 命令消息的免责声明（"Caveat: The messages below
 *   were generated by the user while running local commands..."）；
 * - `command-name` / `command-message` / `command-args` —— 命令本身的回显
 *   （`/clear` 会给出这三个，`command-args` 常为空）；
 * - `local-command-stdout` —— 命令的输出回显。
 *
 * 今后若实测到别的同类包裹标签，往这里加即可 —— 判据只有一个：**剥掉它之后
 * 不该剩下用户的话**。
 */
const SYNTHETIC_TAGS = [
  'local-command-caveat',
  'local-command-stdout',
  'command-name',
  'command-message',
  'command-args',
] as const;

/**
 * 匹配一整段包裹块。收尾用 `\1` 要求**同名标签闭合**，否则 `<command-name>…`
 * 会和后面的 `</command-args>` 错配成一块、把中间的真实内容一并剥掉。允许标签
 * 带属性（实测没有，但带属性的写法不该被漏掉）。
 *
 * 多处使用同一个 /g 正则是安全的：String.prototype.replace 每次从 lastIndex=0
 * 开始执行。
 */
const SYNTHETIC_BLOCK = new RegExp(
  `<(${SYNTHETIC_TAGS.join('|')})(?:\\s[^>]*)?>[\\s\\S]*?<\\/\\1>`,
  'g',
);

/**
 * 这条 user 文本是不是 claude 合成的包裹消息（斜杠命令 / 命令输出）。
 *
 * 判据保守且可解释：**把已知包裹块整段剥掉，剥完只剩空白才算合成**。
 * 于是「用户在正经提问里引用了 `<command-name>/foo</command-name>`」因为还
 * 带着正文而**不会**被判为合成 —— 误杀比漏过滤更糟：用户会看不到自己的问题。
 *
 * 空串 / 纯空白同样返回 true（它也不是用户敲的话）。调用方本来就先过滤空白，
 * 这里保持同一判据，免得两处规则各自漂移。
 *
 * 只认**闭合**的块：截断的标签不剥（剥不干净就成了猜），那种半行本来就过不了
 * JSON.parse，交给上面那层挡。
 */
export function isSyntheticUserText(text: string): boolean {
  return text.replace(SYNTHETIC_BLOCK, '').trim().length === 0;
}

/**
 * 从一段 .jsonl 文本（通常只读了文件头部）里提取 cwd 与首条用户消息（原文）。
 *
 * 「原文」= 只压平空白、不压缩语义（见 condense）—— 用户要认的是「上次在聊的
 * 那个」，任何改写都会让这段话变得不像他自己敲的。
 *
 * 容错是契约：末行多半被截断、某些行类型不熟悉 —— 一律跳过，绝不抛错。
 * 解析不出来就返回空对象，**绝不编造**。
 */
export function parseConversationHead(text: string): { cwd?: string; firstMessage?: string } {
  let cwd: string | undefined;
  let firstMessage: string | undefined;

  for (const raw of text.split('\n')) {
    if (raw.length === 0) continue;
    let o: unknown;
    try {
      o = JSON.parse(raw);
    } catch {
      continue; // 被截断的末行 / 不认识的行
    }
    if (typeof o !== 'object' || o === null) continue;
    const rec = o as Record<string, unknown>;

    if (cwd === undefined && typeof rec.cwd === 'string' && rec.cwd.length > 0) {
      cwd = rec.cwd;
    }
    // 跳过子代理（isSidechain）的消息 —— 那不是用户敲的，认不出终端
    if (firstMessage === undefined && rec.type === 'user' && rec.isSidechain !== true) {
      const msg = rec.message as { content?: unknown } | undefined;
      const t = msg === undefined ? undefined : firstText(msg.content);
      // 斜杠命令的合成包裹消息也不是用户敲的 —— 跳过它继续往下扫，
      // 而不是就此认定「这个会话没有首条消息」（见 isSyntheticUserText）。
      if (t !== undefined && t.trim().length > 0 && !isSyntheticUserText(t)) {
        firstMessage = condense(t);
      }
    }
    if (cwd !== undefined && firstMessage !== undefined) break;
  }

  return {
    ...(cwd !== undefined ? { cwd } : {}),
    ...(firstMessage !== undefined ? { firstMessage } : {}),
  };
}

/**
 * 从一段（通常是**尾部**）jsonl 文本里取**最后一条** ai-title 记录。
 * 一条都没有 / 解析不出 → undefined。
 *
 * 为什么读尾部而不是头部：实测 `ai-title` 是**追加**记录，不是头部字段 ——
 * 一个文件里最多出现 21 次，首次出现位置有 82/184 落在 64 KB 之后，而
 * **最后一次**距 EOF 最远 53887 B。所以从尾部读一个 64 KB 的窗口即可全覆盖。
 *
 * 为什么取最后一条：实测 7/184 个文件的标题真的变过，取最后一条才是当前标题。
 *
 * 容错是契约。注意**截断位置在窗口的首行、不在末行** —— 尾部读是 seek 到
 * 文件中段开始的，第一条记录只有后半截；而末行一直写到 EOF，是完整的。
 * 故「跳过解析不出的行」这条规则同时覆盖两者，别把它理解成「末行不可信」。
 */
export function parseAiTitle(text: string): string | undefined {
  let title: string | undefined;
  for (const raw of text.split('\n')) {
    if (raw.length === 0) continue;
    let o: unknown;
    try {
      o = JSON.parse(raw);
    } catch {
      continue; // 窗口起点处被截断的那一行 / 不认识的行
    }
    if (typeof o !== 'object' || o === null) continue;
    const rec = o as Record<string, unknown>;
    if (rec.type !== 'ai-title') continue;
    const t = rec.aiTitle;
    if (typeof t === 'string' && t.trim().length > 0) title = t;
  }
  return title;
}

/** 只忽略末尾斜杠，其余精确比较（`/a/b` 与 `/a/bc` 不是同一个目录）。 */
function normalize(p: string): string {
  if (p.length === 0) return p;
  const stripped = p.replace(/\/+$/, '');
  return stripped.length === 0 ? '/' : stripped;
}

/** 这条对话是否属于该 cwd —— 归属判据的唯一来源。 */
export function belongsToCwd(candidateCwd: string, cwd: string): boolean {
  if (candidateCwd.length === 0 || cwd.length === 0) return false;
  return normalize(candidateCwd) === normalize(cwd);
}

/**
 * 只保留属于该 cwd 的候选，按 mtime 倒序（最近用过的在前）。
 *
 * mtime 相同时按 id 排序：否则每次弹 QuickPick 的顺序都可能不同，
 * 用户手速快就会选错。
 */
export function candidatesForCwd(
  items: readonly ConversationCandidate[],
  cwd: string,
): ConversationCandidate[] {
  return items
    .filter((c) => belongsToCwd(c.cwd, cwd))
    .slice()
    .sort((a, b) => (b.mtimeMs - a.mtimeMs) || (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
}

/** 体积的可读格式。 */
export function formatBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  const kb = n / 1024;
  if (kb < 1024) return `${kb < 10 ? kb.toFixed(1) : Math.round(kb)} KB`;
  const mb = kb / 1024;
  return `${mb < 10 ? mb.toFixed(1) : Math.round(mb)} MB`;
}

/** 本地时间戳 `YYYY-MM-DD HH:mm`。 */
function localStamp(ms: number): string {
  const d = new Date(ms);
  const p = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`;
}

/**
 * QuickPick 的一行：`<时间> · <首条用户消息原文> · <体积>`。
 * 三样都要有，用户才能认出「就是这个终端」。
 *
 * **只有这一行**：没有第二行（detail），也没有悬停浮层 —— 理由见
 * terminalManager.pickConversation 的说明。
 */
export function formatCandidate(c: ConversationCandidate): string {
  return `${localStamp(c.mtimeMs)} · ${c.firstMessage.length > 0 ? c.firstMessage : '（无首条消息）'} · ${formatBytes(c.bytes)}`;
}

/**
 * 选择框末尾那项。**开新对话只能由用户主动选它**，绝不由「取消」隐式产生 ——
 * 取消是没有结论，不是「给我开一条新的」。
 */
export const NEW_CONVERSATION_LABEL = '＋ 新建一条对话（不复用任何历史）';

/** 一条「条目 ↔ 对话」绑定关系的最小视角（只取判归属要用的字段）。 */
export interface BindingView {
  id: string;
  name: string;
  conversationId?: string;
}

/**
 * 收集「这个对话 id 已经被哪个条目绑走了」。
 *
 * 用途：在候选列表里把别人的对话标出来，并在选中时要求二次确认 ——
 * 两个终端接同一条对话会让两个 claude 进程同时写同一个 `.jsonl`。
 *
 * - **跳过自己**：自己当然绑着这条，不是冲突。
 * - 跳过未绑定的（undefined / 空串）。
 * - 同一个 id 被多条条目绑着时取**先出现**的那个：顺序稳定，不随列表
 *   抖动而变化。
 */
export function ownersOf(
  entries: readonly BindingView[],
  selfId: string,
): Map<string, string> {
  const owners = new Map<string, string>();
  for (const e of entries) {
    if (e.id === selfId) continue;
    const id = e.conversationId;
    if (id === undefined || id.length === 0) continue;
    if (!owners.has(id)) owners.set(id, e.name);
  }
  return owners;
}

/**
 * 选择框里的一行：普通候选就是 `formatCandidate`，已被别的条目绑走时
 * 附上归属者 —— 让用户能看出「这是别人的」，而不是选完才知道。
 */
export function formatCandidateWithOwner(c: ConversationCandidate, owner?: string): string {
  const base = formatCandidate(c);
  return owner === undefined ? base : `${base} · 已绑给「${owner}」`;
}
