/**
 * 「条目 ↔ claude 对话」的纯逻辑：候选枚举的解析与筛选、显示格式化。
 *
 * 本文件刻意不依赖 vscode，也不碰文件系统（IO 在 src/conversationFiles.ts），
 * 以便脱离编辑器直接单测。
 *
 * 背景（2026-09-10，实测结论，勿改）：
 * - `claude --resume <uuid>` **是按 cwd 作用域**的：从别的 cwd 运行会报
 *   `No conversation found with session ID`。所以恢复必须在条目自己的 cwd
 *   里 launch —— 扩展本来就是用 `-c cwd` 建会话，天然满足。
 * - 会话文件里记录了 `"cwd":"<绝对路径>"` 字段。**枚举候选一律按这个字段
 *   筛，不要去猜 project 目录名的转义规则**（实测 `_` 和 `.` 也会被换成
 *   `-`，规则不可靠）。
 * - claude 进程不长期持有 .jsonl 的 fd，无法从 /proc 反查运行中会话的 id，
 *   因此绑定关系只能由扩展自己记（见 types.ts 的 conversationId）。
 */

/** 一条可接回的对话（由 ~/.claude/projects 下的 .jsonl 枚举而来）。 */
export interface ConversationCandidate {
  /** 对话 id = 会话文件名（去掉 .jsonl），即 `--resume` 的参数 */
  id: string;
  /** 会话文件里记录的 cwd —— 权威的归属判据 */
  cwd: string;
  /** 文件 mtime（毫秒），用于倒序 */
  mtimeMs: number;
  /** 文件体积（字节），用于在列表里辨认 */
  bytes: number;
  /** 首条用户消息的摘要；取不到为空串 */
  summary: string;
  /**
   * **最后**一个真实用户问题（已压平截断）；取不到时整个字段缺省。
   *
   * 只在**按 cwd 过滤之后**才填（见 conversationFiles 的 listConversationsForCwd）：
   * 全量枚举那 290+ 个文件时读尾部是纯浪费。
   */
  lastQuestion?: string;
  /** **最后**一条助手回答的正文（已压平截断）；取不到时整个字段缺省 */
  lastAnswer?: string;
}

/** 摘要最长字符数 —— QuickPick 一行装不下更多，也够认出「就是这个终端」。 */
const SUMMARY_MAX = 60;

/** 详情行（QuickPick 项的第二行小字）里「最后的问题」的长度上限。 */
const QUESTION_MAX = 80;

/**
 * 悬停浮层里「最后的回答」的长度上限。
 *
 * 比列表行宽松得多（浮层本来就为放长文而生），但仍要截断 —— 一条回答可以有几
 * KB，整段塞进 tooltip 既读不动也白白占内存。
 */
const ANSWER_MAX = 200;

/** 从 user 消息的 content 里取纯文本（可能是字符串，也可能是分块数组）。 */
function firstText(content: unknown): string | undefined {
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) {
    for (const block of content) {
      if (typeof block !== 'object' || block === null) continue;
      const b = block as { type?: unknown; text?: unknown };
      // 只认 text 块：tool_result 是工具回执，不是用户敲进去的话
      if (b.type === 'text' && typeof b.text === 'string') return b.text;
    }
  }
  return undefined;
}

/**
 * 从 assistant 消息的 content 里取**最后一个非空** text 块。
 *
 * 与 firstText 相对：assistant 的一轮常常是「说一句 + 一串 tool_use」，真正
 * 说出口的话往往是最后一个 text 块，正着取会拿到过渡语。
 *
 * **只认非空块**（`trim().length > 0`）。实测末尾常跟一个纯空白的 text 块
 * （`'   '`）；若把它当成「最后一个 text 块」返回，调用点只会判为「取不到」
 * 而**直接放弃**，前面那个真正说了话的块就再也轮不到了 —— 这与本函数
 * 「最后一个**非空** text 块」的契约不符。跳过空块继续往前找，才拿得到
 * 用户真正看到的那句话。
 *
 * 判空收口在这一处：调用点（parseConversationTail）无需再对同一件事设第二
 * 道闸，否则「空块」的语义会散在两处，改一处漏一处。
 */
function lastText(content: unknown): string | undefined {
  if (Array.isArray(content)) {
    for (let i = content.length - 1; i >= 0; i--) {
      const block = content[i];
      if (typeof block !== 'object' || block === null) continue;
      const b = block as { type?: unknown; text?: unknown };
      // 空白块不是「说出口的话」：跳过它，继续往前找那个真正有内容的
      if (b.type === 'text' && typeof b.text === 'string' && b.text.trim().length > 0) {
        return b.text;
      }
    }
  }
  return undefined;
}

/**
 * 压平空白并截断，避免多行摘要在列表里错位。
 *
 * max 默认取 SUMMARY_MAX（QuickPick 一行的高度）；tooltip 那类放得下长文的地方
 * 显式传更大的值 —— 默认值必须保持原样，既有的调用与测试都钉在 60 上。
 */
function condense(text: string, max: number = SUMMARY_MAX): string {
  const flat = text.replace(/\s+/g, ' ').trim();
  return flat.length > max ? `${flat.slice(0, max)}…` : flat;
}

/**
 * claude 把**斜杠命令**写成合成的 user 消息。它不是用户敲进去的话，但长得和
 * 用户消息一模一样 —— 不识别的话，一条以 `/clear` 开头的会话，其首条 user
 * 消息就是这些包裹文本，列表里整个摘要都成了噪音。
 *
 * 下面这几个标签是**本机 transcript 实测到的原文**，不是猜的：
 * - `local-command-caveat` —— 命令消息的免责声明（"Caveat: The messages below
 *   were generated by the user while running local commands..."）；
 * - `command-name` / `command-message` / `command-args` —— 命令本身的回显
 *   （`/clear` 会给出这三个，`command-args` 常为空）；
 * - `local-command-stdout` —— 命令的输出回显。
 *
 * 今后若实测到别的同类包裹标签，往这里加即可 —— 判据只有一个：**剥掉它之后
 * 不该剩下用户的话**。
 */
const SYNTHETIC_TAGS = [
  'local-command-caveat',
  'local-command-stdout',
  'command-name',
  'command-message',
  'command-args',
] as const;

/**
 * 匹配一整段包裹块。收尾用 `\1` 要求**同名标签闭合**，否则 `<command-name>…`
 * 会和后面的 `</command-args>` 错配成一块、把中间的真实内容一并剥掉。允许标签
 * 带属性（实测没有，但带属性的写法不该被漏掉）。
 *
 * 多处使用同一个 /g 正则是安全的：String.prototype.replace 每次从 lastIndex=0
 * 开始执行。
 */
const SYNTHETIC_BLOCK = new RegExp(
  `<(${SYNTHETIC_TAGS.join('|')})(?:\\s[^>]*)?>[\\s\\S]*?<\\/\\1>`,
  'g',
);

/**
 * 这条 user 文本是不是 claude 合成的包裹消息（斜杠命令 / 命令输出）。
 *
 * 判据保守且可解释：**把已知包裹块整段剥掉，剥完只剩空白才算合成**。
 * 于是「用户在正经提问里引用了 `<command-name>/foo</command-name>`」因为还
 * 带着正文而**不会**被判为合成 —— 误杀比漏过滤更糟：用户会看不到自己的问题。
 *
 * 空串 / 纯空白同样返回 true（它也不是用户敲的话）。调用方本来就先过滤空白，
 * 这里保持同一判据，免得两处规则各自漂移。
 *
 * 只认**闭合**的块：截断的标签不剥（剥不干净就成了猜），那种半行本来就过不了
 * JSON.parse，交给上面那层挡。
 */
export function isSyntheticUserText(text: string): boolean {
  return text.replace(SYNTHETIC_BLOCK, '').trim().length === 0;
}

/**
 * 从一段 .jsonl 文本（通常只读了文件头部）里提取 cwd 与首条用户消息摘要。
 *
 * 容错是契约：末行多半被截断、某些行类型不熟悉 —— 一律跳过，绝不抛错。
 * 解析不出来就返回空对象，**绝不编造**。
 */
export function parseConversationHead(text: string): { cwd?: string; summary?: string } {
  let cwd: string | undefined;
  let summary: string | undefined;

  for (const raw of text.split('\n')) {
    if (raw.length === 0) continue;
    let o: unknown;
    try {
      o = JSON.parse(raw);
    } catch {
      continue; // 被截断的末行 / 不认识的行
    }
    if (typeof o !== 'object' || o === null) continue;
    const rec = o as Record<string, unknown>;

    if (cwd === undefined && typeof rec.cwd === 'string' && rec.cwd.length > 0) {
      cwd = rec.cwd;
    }
    // 跳过子代理（isSidechain）的消息 —— 那不是用户敲的，认不出终端
    if (summary === undefined && rec.type === 'user' && rec.isSidechain !== true) {
      const msg = rec.message as { content?: unknown } | undefined;
      const t = msg === undefined ? undefined : firstText(msg.content);
      // 斜杠命令的合成包裹消息也不是用户敲的 —— 跳过它继续往下扫，
      // 而不是就此认定「这个会话没有摘要」（见 isSyntheticUserText）。
      if (t !== undefined && t.trim().length > 0 && !isSyntheticUserText(t)) {
        summary = condense(t);
      }
    }
    if (cwd !== undefined && summary !== undefined) break;
  }

  return {
    ...(cwd !== undefined ? { cwd } : {}),
    ...(summary !== undefined ? { summary } : {}),
  };
}

/**
 * 从一段（通常是**尾部**的）jsonl 文本里取**最后**一个用户问题与**最后**一条
 * 助手回答，供 QuickPick 的 detail / tooltip 显示。
 *
 * 为什么要读尾部：头部的首条消息只能说明「这个会话在讲什么」，而用户要认的是
 * 「哪一条是我上次在聊的那个」—— 最后聊的内容才最接近他的记忆。
 *
 * 容错是契约，与 parseConversationHead 完全一致：解析不出的行一律跳过、绝不抛错，
 * 取不到就不给那个字段，**绝不编造**。尾部窗口的起点落在某条记录中间，所以
 * 「跳过解析不出的行」在这里首先要挡的就是那个半行 —— 它必然 JSON.parse 失败。
 *
 * 用户问题的判据与头部同一套：`type === 'user'`、非子代理、`firstText` 拿得到、
 * 且**不是合成包裹消息**。倒着扫，第一个命中的就是最后那一问；若最后一条恰好是
 * 斜杠命令，会自然往前找到真正的提问。`firstText` 只认 text 块，所以 tool_result
 * 回执天然不会被当成用户提问 —— 这是对的，回执不是他说的话。
 *
 * 回答取 `message.content` 里**最后一个**非空 text 块（见 lastText）。子代理
 * （isSidechain）的产出不是这个终端在聊的内容，与头部同一判据，一并跳过。
 *
 * 两段文本都在这里压平截断（回答的上限更宽松）：返回的就是能直接塞进 QuickPick
 * 的形状，调用方不必再各自截一遍。
 */
export function parseConversationTail(text: string): { question?: string; answer?: string } {
  let question: string | undefined;
  let answer: string | undefined;

  const lines = text.split('\n');
  for (let i = lines.length - 1; i >= 0; i--) {
    if (question !== undefined && answer !== undefined) break;
    const raw = lines[i];
    if (raw.length === 0) continue;
    let o: unknown;
    try {
      o = JSON.parse(raw);
    } catch {
      continue; // 窗口起点处被截断的半行 / 不认识的行
    }
    if (typeof o !== 'object' || o === null) continue;
    const rec = o as Record<string, unknown>;
    if (rec.isSidechain === true) continue; // 子代理的消息，不是这个终端在聊的内容

    const msg = rec.message as { content?: unknown } | undefined;
    if (question === undefined && rec.type === 'user') {
      const t = msg === undefined ? undefined : firstText(msg.content);
      if (t !== undefined && t.trim().length > 0 && !isSyntheticUserText(t)) {
        question = condense(t, QUESTION_MAX);
      }
    } else if (answer === undefined && rec.type === 'assistant') {
      const t = msg === undefined ? undefined : lastText(msg.content);
      // 只判 undefined：lastText 已保证返回的必是**非空** text 块，这里不再
      // 重复 trim 判空 —— 对同一件事设两道闸，改了 lastText 还得记得改这里。
      if (t !== undefined) answer = condense(t, ANSWER_MAX);
    }
  }

  return {
    ...(question !== undefined ? { question } : {}),
    ...(answer !== undefined ? { answer } : {}),
  };
}

/**
 * 从一段（通常是**尾部**）jsonl 文本里取**最后一条** ai-title 记录。
 * 一条都没有 / 解析不出 → undefined。
 *
 * 为什么读尾部而不是头部：实测 `ai-title` 是**追加**记录，不是头部字段 ——
 * 一个文件里最多出现 21 次，首次出现位置有 82/184 落在 64 KB 之后，而
 * **最后一次**距 EOF 最远 53887 B。所以从尾部读一个 64 KB 的窗口即可全覆盖。
 *
 * 为什么取最后一条：实测 7/184 个文件的标题真的变过，取最后一条才是当前标题。
 *
 * 容错是契约。注意**截断位置在窗口的首行、不在末行** —— 尾部读是 seek 到
 * 文件中段开始的，第一条记录只有后半截；而末行一直写到 EOF，是完整的。
 * 故「跳过解析不出的行」这条规则同时覆盖两者，别把它理解成「末行不可信」。
 */
export function parseAiTitle(text: string): string | undefined {
  let title: string | undefined;
  for (const raw of text.split('\n')) {
    if (raw.length === 0) continue;
    let o: unknown;
    try {
      o = JSON.parse(raw);
    } catch {
      continue; // 窗口起点处被截断的那一行 / 不认识的行
    }
    if (typeof o !== 'object' || o === null) continue;
    const rec = o as Record<string, unknown>;
    if (rec.type !== 'ai-title') continue;
    const t = rec.aiTitle;
    if (typeof t === 'string' && t.trim().length > 0) title = t;
  }
  return title;
}

/** 只忽略末尾斜杠，其余精确比较（`/a/b` 与 `/a/bc` 不是同一个目录）。 */
function normalize(p: string): string {
  if (p.length === 0) return p;
  const stripped = p.replace(/\/+$/, '');
  return stripped.length === 0 ? '/' : stripped;
}

/** 这条对话是否属于该 cwd —— 归属判据的唯一来源。 */
export function belongsToCwd(candidateCwd: string, cwd: string): boolean {
  if (candidateCwd.length === 0 || cwd.length === 0) return false;
  return normalize(candidateCwd) === normalize(cwd);
}

/**
 * 只保留属于该 cwd 的候选，按 mtime 倒序（最近用过的在前）。
 *
 * mtime 相同时按 id 排序：否则每次弹 QuickPick 的顺序都可能不同，
 * 用户手速快就会选错。
 */
export function candidatesForCwd(
  items: readonly ConversationCandidate[],
  cwd: string,
): ConversationCandidate[] {
  return items
    .filter((c) => belongsToCwd(c.cwd, cwd))
    .slice()
    .sort((a, b) => (b.mtimeMs - a.mtimeMs) || (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
}

/** 体积的可读格式。 */
export function formatBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  const kb = n / 1024;
  if (kb < 1024) return `${kb < 10 ? kb.toFixed(1) : Math.round(kb)} KB`;
  const mb = kb / 1024;
  return `${mb < 10 ? mb.toFixed(1) : Math.round(mb)} MB`;
}

/** 本地时间戳 `YYYY-MM-DD HH:mm`。 */
function localStamp(ms: number): string {
  const d = new Date(ms);
  const p = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`;
}

/**
 * QuickPick 的一行：`<时间> · <首条用户消息摘要> · <体积>`。
 * 三样都要有，用户才能认出「就是这个终端」。
 */
export function formatCandidate(c: ConversationCandidate): string {
  return `${localStamp(c.mtimeMs)} · ${c.summary.length > 0 ? c.summary : '（无摘要）'} · ${formatBytes(c.bytes)}`;
}

/**
 * QuickPick 项的 **detail**（常显的第二行小字）：最后那一问。
 *
 * 只放问题、不放回答：detail 就一行小字，把回答也塞进去只会两头都看不全 ——
 * 回答留给悬停浮层（见 formatCandidateTooltip）。没有可显示的问答时返回
 * undefined，让浮动列表少一行空行，而不是显示一行「最后问：」。
 */
export function formatCandidateDetail(c: ConversationCandidate): string | undefined {
  const q = c.lastQuestion;
  return q === undefined || q.length === 0 ? undefined : `最后问：${q}`;
}

/**
 * 悬停浮层的 **markdown 源**，由 vscode 侧包成 `MarkdownString`。
 *
 * 返回源文本而不是 MarkdownString，是为了让本文件维持零 vscode 依赖、能脱离
 * 编辑器直接单测（本文件头部的约定）。段落之间必须留**空行**：markdown 会把
 * 单个换行折叠成空格，问答就糊成一行了。
 */
export function formatCandidateTooltip(c: ConversationCandidate): string | undefined {
  const parts: string[] = [];
  if (c.lastQuestion !== undefined && c.lastQuestion.length > 0) {
    parts.push(`最后的问题：${c.lastQuestion}`);
  }
  if (c.lastAnswer !== undefined && c.lastAnswer.length > 0) {
    parts.push(`最后的回答：${c.lastAnswer}`);
  }
  return parts.length === 0 ? undefined : parts.join('\n\n');
}

/**
 * 选择框末尾那项。**开新对话只能由用户主动选它**，绝不由「取消」隐式产生 ——
 * 取消是没有结论，不是「给我开一条新的」。
 */
export const NEW_CONVERSATION_LABEL = '＋ 新建一条对话（不复用任何历史）';

/** 一条「条目 ↔ 对话」绑定关系的最小视角（只取判归属要用的字段）。 */
export interface BindingView {
  id: string;
  name: string;
  conversationId?: string;
}

/**
 * 收集「这个对话 id 已经被哪个条目绑走了」。
 *
 * 用途：在候选列表里把别人的对话标出来，并在选中时要求二次确认 ——
 * 两个终端接同一条对话会让两个 claude 进程同时写同一个 `.jsonl`。
 *
 * - **跳过自己**：自己当然绑着这条，不是冲突。
 * - 跳过未绑定的（undefined / 空串）。
 * - 同一个 id 被多条条目绑着时取**先出现**的那个：顺序稳定，不随列表
 *   抖动而变化。
 */
export function ownersOf(
  entries: readonly BindingView[],
  selfId: string,
): Map<string, string> {
  const owners = new Map<string, string>();
  for (const e of entries) {
    if (e.id === selfId) continue;
    const id = e.conversationId;
    if (id === undefined || id.length === 0) continue;
    if (!owners.has(id)) owners.set(id, e.name);
  }
  return owners;
}

/**
 * 选择框里的一行：普通候选就是 `formatCandidate`，已被别的条目绑走时
 * 附上归属者 —— 让用户能看出「这是别人的」，而不是选完才知道。
 */
export function formatCandidateWithOwner(c: ConversationCandidate, owner?: string): string {
  const base = formatCandidate(c);
  return owner === undefined ? base : `${base} · 已绑给「${owner}」`;
}
